### ISSUE TITLE
Can't inline critical css (FOUC)

### ISSUE THREAD

**Issue by vandelpavel** [freddy38510/quasar-app-extension-ssg#162]
Just created this repo where you can see that after serving the ssg build we can see a FOUC (flash of unstyled contet). You can examin better the situation by disabling js ```F12 > ctrl + shift + p > Disable javascript```
https://github.com/vandelpavel/ssg-test-critical-css

**Comment by freddy38510** [comment]
Thanks for having created a reproduction repository :)

Which content is concerned exactly ?

The only thing I can see is a FOUT (Flash of Unstyled Text).

**Comment by freddy38510** [comment]
You were right, the style of index.vue file is not inlined which causes a FOUC.

It seems that adding  the `vue-svg-inline-loader` loader to the webpack rules with the method `extendWebpack` breaks something.

The style is correctly inlined if you use `chainWebpack` instead of `extendWebpack` in your `quasar.conf.js` file.

Please try replacing the method `extendWebpack` by this one:
```javascript
chainWebpack: config => {
  config.module
    .rule("vue")
    .use("vue-svg-inline-loader")
    .loader("vue-svg-inline-loader")
    .options({ addTitle: true, });
}
```

Let me know if there is any FOUC after this change.

**Comment by vandelpavel** [comment]
Thank you!
