### ISSUE TITLE
Prompt option: setup critical CSS inlining

### ISSUE THREAD

**Issue by IlCallo** [freddy38510/quasar-app-extension-ssg#23]
Premises are the same as #21 

Adding an option for critical CSS inlining is an easily automatable task, an AE prompt to the dev will be a better push to this best-practice instead of asking him to copy/paste the same code from the README

**Comment by freddy38510** [comment]
Initially i didn't want to make the extension too opinionated. But after thinking of it, users could disable this feature then do it themself the way they want, with the library they want.

For memory leaking issue, we could generate critical CSS every time a page is rendered before writing it to a file. Instead of doing it after all pages have been generated.

What do you think about that ? @IlCallo

**Comment by IlCallo** [comment]
> Initially i didn't want to make the extension too opinionated. But after thinking of it, users could disable this feature then do it themself the way they want, with the library they want.

I meant that you could automatically add the code you provide in the README if the user select that feature into prompts, but baked in support is good too, I don't really have an opinion on this right now

> For memory leaking issue, we could generate critical CSS every time a page is rendered before writing it to a file. Instead of doing it after all pages have been generated.

Unluckily, I don't have much experience in this field too... Are there cases where you do need to have all files processed to calculate the critical CSS? If not, I guess doing it on a "per file" basis could speed up the generation
