### ISSUE TITLE
quasar-ui-qmediaplayer not building

### ISSUE THREAD

**Issue by danbars** [freddy38510/quasar-app-extension-ssg#230]
Not sure if this is an issue with `quasar-ui-qmediaplayer` or with this project.
I have a quasar site with `quasar-ui-qmediaplayer` package, and when I try to `build:ssg` I get the following error:

```
[  Error: /Users/xxx/xxx/xxx-site/node_modules/@quasar/quasar-ui-qmediaplayer/dist/index.cjs.js
  require() of ES modules is not supported.
  require() of /Users/xxx/xxx/xxx-site/node_modules/@quasar/quasar-ui-qmediaplayer/dist/index.cjs.js from /Users/xxx/xxx/xxx-site/node_modules/.cache/quasar-app-extension-ssg is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
  Instead rename index.cjs.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/xxx/xxx/xxx-site/node_modules/@quasar/quasar-ui-qmediaplayer/package.json.
```

If I rename `index.cjs.js` inside `node_modules` to `index.cjs` and update its `package.json` file with `"main": "index.cjs"` the build passes. This might indicate that this is an issue with the other package. 
However, I believe that their build is standard and these files are named like this by default.
Is this something that this project can fix, or is there something wrong with `quasar-ui-qmediaplayer`'s build?

**Comment by freddy38510** [comment]
Hello,

I found the [same issue](https://github.com/quasarframework/quasar-ui-qmediaplayer/issues/356) which happens with ssr mode too.

I believe that the filenames are fine. It looks like the [`"type": "module"` line should be removed in the `package.json` file ](https://github.com/quasarframework/quasar-ui-qmediaplayer/blob/next/ui/package.json#L7)in order to use their component at server-side.
