### ISSUE TITLE
body.screen-- classes don't seem to work

### ISSUE THREAD

**Issue by eyedean** [freddy38510/quasar-app-extension-ssg#231]
Greetings,

I am using some CSS (Stylus) rules on some of my components that depend on `body.screen--` classes. I do have Quasar's [bodyClasses](https://v1.quasar.dev/options/screen-plugin#how-to-enable-body-classes) enabled in my `quasar.conf.js`.

It works in dev (serving as SPA) mode, but when I build it for SSG, these CSS rules don't even appear in the inline CSS source.

For instance, in the example below, I can find the `background red` rule in the view-source:// of the output, but not the `color blue` role.

```stylus
.my-class
    background red
    body.screen--xs &
        color blue
```

Other notes:
1. I do see `screen--xs` on `body` in Chrome, but the rule doesn't show up at all.
1. [Visibility media classes](https://v1.quasar.dev/style/visibility#window-width-related) (e.g. `sm`) do work. So it shouldn't be a media query problem.
1. If I string-search for this rule, I find it in one of the `.js` output files, but not in any inline CSS values in HTML files, or any .css file. Is that where non-critical-CSS values should go?
1. FWIW, I am using Vue SFC + TS.
1. Finally, I tried replacing `body.screen-xs &` with `@media(max-width: 300px) &` and it does work!
```stylus
.my-class
    @media(max-width: 400px)
        &
            color red
```

**Comment by freddy38510** [comment]
Hello,

I guess that the css rule named `screen-xs` is dropped when using the option [`inlineCriticalCss`](https://github.com/freddy38510/quasar-app-extension-ssg/tree/2.x#inlinecriticalcss).

This is because the css rule is not present in the HTML string **at server-side** when [beastcss](https://github.com/freddy38510/beastcss) is processing it.

These classes are injected dynamically into the document **at client-side** because they are based on Browser’s User Agent.

What you can do is to [whitelist ](https://github.com/freddy38510/beastcss#whitelist) this css rule:

```javascript
// quasar.conf.js
{
  ssg: {
    inlineCriticalCss: {
      whitelist: [/screen-xs/]
    }
  }
}
```

Please, let me know if it works.

**Comment by eyedean** [comment]
Hi @freddy38510,

I am back to this after a year and wanted to let you know that your solution (using `whitelist`) worked!

Thank you.
