### ISSUE TITLE
Move extension configuration to a `ssg` property on `quasar.config.js`

### ISSUE THREAD

**Issue by IlCallo** [freddy38510/quasar-app-extension-ssg#3]
Configuration of this AE should probably be moved to a `ssg` property into `quasar.config.js` instead of relaying on `ssr` configuration.
Defaults could still be taken automatically by SSR configuration, the idea is only to allow people to override those without affecting SSR builds too.

In this way it would be easier for devs to generate different apps for `ssg` and `ssr`, instead of having to chose one of the 2.

This would also mean to provide adequate TS types augmenting `QuasarConf` and `QuasarContext` interfaces, to provide intellisense.

**Comment by freddy38510** [comment]
@IlCallo 
I made a lot of changes without commiting it. So, i decided to rename the master branch to "v0.0.1".
Then, i made a new master branch with only one commit including all the previous code with all the changes i talked about.

This way, i hope to keep a clean history and use conventionnal naming of commits.

You can see in the updated docs that the configuration has been moved to `ssg` key (or property ?)  on `quasar-conf.js`.

Fixed in https://github.com/freddy38510/quasar-app-extension-ssg/commit/2bab4ff83e29cbdbc61a4c1b73e8208725a10557
