### ISSUE TITLE
Failed to install quasar-app-extension-ssg

### ISSUE THREAD

**Issue by 10hamachi** [freddy38510/quasar-app-extension-ssg#34]
quasar ext add ssg
 App · Installing "ssg" Quasar App Extension

 App · Retrieving "quasar-app-extension-ssg"...
 App · [sync] Running "npm install --save-dev quasar-app-extension-ssg"

npm ERR! path git
npm ERR! code ENOENT
npm ERR! errno ENOENT
npm ERR! syscall spawn git
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t https://github.com/freddy38510/critters.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\hamana.keigo\AppData\Roaming\npm-cache\_logs\2020-12-30T01_48_54_977Z-debug.log

 App · ⚠️  Command "npm" failed with exit code: 1
 App · ⚠️  Failed to install quasar-app-extension-ssg

**Comment by freddy38510** [comment]
Seems to be the same error than [this issue](https://github.com/freddy38510/quasar-app-extension-ssg/issues/29).

The [`Critters` dependency](https://github.com/freddy38510/quasar-app-extension-ssg/blob/ce861a95ccf96c5ad7ed369c757784a50dd1b4b6/package.json#L46) in the AE requires **`git`** to be installed on your system, to let `npm` fetch it.

This is because i fork [`Critters`](https://github.com/GoogleChromeLabs/critters) and i didn't publish it yet on npm. I will do it later, but for now, you should install `git` on your system.
