### ISSUE TITLE
Demo is no longer can be used as a template

### ISSUE THREAD

**Issue by kostyfisik** [freddy38510/quasar-app-extension-ssg#346]
@freddy38510  After switch to monorepo is seems that it is no longer possible to use "demo" project (renamed to "playground") as a template. Previously (last working commit for this workflow is of May 4, 2023) I just copied quasar-ssg-vite directory out of tree and it worked (yarn install, quasar ssg dev). Have you considered to provide a template for quasar+ssg+vite project?

**Comment by kostyfisik** [comment]
It works with current master, however, it need's a bit of hacking (and I don't now, if it is a good way to go...)

    git clone git@github.com:freddy38510/quasar-app-extension-ssg.git
    cp -r quasar-app-extension-ssg/playground/quasar-cli-with-vite/ ./
    cd quasar-cli-with-vite
    cp ../quasar-app-extension-ssg/.npmrc ./
    # update package.json with "quasar-app-extension-ssg": "^4.7.0"
    pnpm i rollup@^2 postcss ouch
    quasar ssg dev

I am a bit worried that it only works with rollup@^2... while ver 3 was available long ago...

**Comment by freddy38510** [comment]
Hey @kostyfisik,

With the latest commits, the demo should works. At least it does on Netlify.

In the [updated readme](https://github.com/freddy38510/quasar-app-extension-ssg#contributing) you'll find all the steps you need to follow to develop the extension locally.

Let me know if you have any  issues. More changes to come. That's why there's no new release yet.

**Comment by kostyfisik** [comment]
Dear @freddy38510,

Great news! I am overly interested seeing the upcoming release, thank you a lot!
