### ISSUE TITLE
Can it possibly be used with quasar 2?

### ISSUE THREAD

**Issue by kosirm** [freddy38510/quasar-app-extension-ssg#36]
Sorry if it is stupid question... I'm pretty new here. Thanks.

**Comment by kosirm** [comment]
I just found out that Quasar 2 doesn't have SSR support yet due to some Vue issues. Anyway I'm interested to know if you plan to make this work on Quasar 2 when SSR will be available? Thanks.

**Comment by freddy38510** [comment]
Hi @kosirm ,

Yes, for sure i'm planning to do it, as soon as Quasar 2 stable version with SSR support is out.

**Comment by kosirm** [comment]
Thanks!

**Comment by Nisgrak** [comment]
Hey @freddy38510!

Quasar just make the v2 stable, I would love to have this extension.

Thanks for all your work 😄

**Comment by freddy38510** [comment]
Hey @Nisgrak

I'm actually implementing new features, i'm very close to finish. Then i will make this extension compatible with Quasar v2 :)

Any help is welcome, feel free to make some PR if you want.

The features i'm talking about are:

- Get routes to generate from the App router. (DONE)
- A crawler to find dynamic routes and generate them. (DONE)
- A better concurrency management with queue instead of batches. (DONE)
- Use a published version of my own Critters fork which i'm trying to make it faster to process html and css. (Almost DONE)

**Comment by lukadriel7** [comment]
This feature is really what quasar lacks at the moment. I hope they will integrate it to the main project.

**Comment by lukadriel7** [comment]
Hello, just checking to see if the project is still being developed

**Comment by freddy38510** [comment]
Hello @lukadriel7,

I am working hard on it even if i didn't push a commit since a while.

I will come with a solution for FOUC issue in the next days. Then i will start working on Quasar v2. Any PR is welcome by the way :)

**Comment by freddy38510** [comment]
@lukadriel7,

The features i was talking about since many weeks are now done and new versions published.

Now i can work on Quasar v2 support. I will put some feedback here about the progress of the development.

Meanwhile you can upgrade to quasar-app-extension@2.0.0. I will be glad if you tell me how it works, and hopefully no new issues discovered :)

**Comment by lostnet** [comment]
> Ps: By critical i mean all rules used by the document, not just above-the-fold.

Tuning for above/bellow the fold without adding client side computation struck me as theoretically impossible since a client shouldn't communicate unique screen dimensions like a portrait mode monitor which might make many things above the fold that other clients shouldn't load. But I am interested in testing other aspects to test ways to improve mobile lighthouse performance.

I took a stab at trying to implement this quasar2/webpack5 support but it seemed a bit too difficult as a first project, but I'll take a look at how you implement it and hopefully understand enough to start experimenting with some modifications.

The other aspect of quasar2 that interests me is that the vue2 router's addition of trailing slashes was mandatory and creates a problem similar to FOUC when it routes from a landing page with no slash. I'd be happy to test out these routes with static and crawl routes on any beta versions, etc.

Thanks!

**Comment by freddy38510** [comment]
@lostnet,

You are absolutely right about critical css above the fold. One possibility is to generate critical css above the fold for multiple resolutions based on average clients that uses your web app. This is not perfect and i doubt that you can obtain a significant performance improvement.

From the tests i did, purging quasar css from unused rules is a good starting point.
There is also a improvement window about fonts. The default behavior with fonts coming from @quasar/extras has a noticable impact on performance.

Could you elaborate on the trailing slashes with vue2 router's ? Are you talking about a 301 redirection in case of a missing trailing slash ? At first-load in a browser or during server side rendering ?

**Comment by lostnet** [comment]
> The default behavior with fonts coming from @quasar/extras has a noticable impact on performance.

For fonts I went with the new fad of trying to get the best builtin font:

```
body * {
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Liberation Sans", sans-serif;
}
```

But having a decent font uniformly loading would be a great improvement as this ends up looking better in some browsers than others.

> Could you elaborate on the trailing slashes with vue2 router's ? Are you talking about a 301 redirection in case of a missing trailing slash ? At first-load in a browser or during server side rendering ?

Sorry this was just the 301 redirection, I was/am confused since some of our analytics makes it look more like we had this [router issue](https://github.com/vuejs/vue-router/issues/2945) which has come up before with our SPA setup app.

**Comment by freddy38510** [comment]
There is many ways to handle fonts to improve performance and user experience. This could lead to a very long conversation :) Let's try to focus on the issue.

About 301 redirection this is handled by the app extension since v2.0.0 and specifically this [commit](https://github.com/freddy38510/quasar-app-extension-ssg/commit/6ffb2cf7b9c1087f098005cf3eda53b8e013a399).
The app extension is "agnostic" about if there are trailing slashes or not in your Vue router routes option, provided routes from AE `ssg.routes` option and crawled routes.
If Vue router's make a 301 redirection during pre-rendering of a route, the app extension pre-render the redirected route instead.

About performance i made some tests with a fresh new quasar v2 project and the ported AE SSG in development. Lighthouse reported a score of **100** points in performance with critical css inlined + async loading of stylesheets instead of **90** without it.
The only downside is that it leads to some duplicated css rules in the document. The ones that are inlined and the ones from async loaded stylesheets.

So i think i will re-add this feature in the next version of the AE with Quasar v2 support. I should backport this feature to the previous version too.

**Comment by lostnet** [comment]
Thanks @freddy38510, it works great desktop remains **95-100%** with the new version and mobile has gone up to about **76-77%** from **40-45%** with the previous versions.

**Comment by freddy38510** [comment]
Did you use the latest 3.x version with Quasar v2 supports ?

It's a great improvement on mobile, i'm glad this is useful for you. It could have a negative impact on performance if you have a lot of css inlined in the html document making it too big to download and parse for the browser. Maybe i should add a threshold option to not inline critical css above a certain size in bytes.

I'm thinking of an other feature which purge unused css from quasar css vendor file. I could use beastcss but i fear that it will drop used css rules like transitions classes and others. Another possibility is using [purgecss](https://purgecss.com/) but we need a way to know which quasar ui components is used by the app to include them in the `content` option. But before implementing this feature, i should test if the performance improvement is significant or not.

**Comment by lostnet** [comment]
> Did you use the latest 3.x version with Quasar v2 supports ?

Yes, I'd already tested quasar v2 in spa mode so the main things to migrate were for ssr mode and use of Meta. Everything for this extension was seamless.

> Maybe i should add a threshold option to not inline critical css above a certain size in bytes.

We migrated an older site so we started with a lot of legacy CSS, but we replaced pretty much all of it with close to default quasar components. For that kind of migration being able to refer to separate stylesheets in a way that wouldn't be in-lined was enough. I think a method to trim some of the unused quasar css would be more likely to have influence on our mobile lighthouse as vendor.css is 16X larger than the app.css in our build. But I will also do some manual modifications to test where we could gain points on mobile.
