### ISSUE TITLE
Add minimal README

### ISSUE THREAD

**Issue by IlCallo** [freddy38510/quasar-app-extension-ssg#6]
There are some things which aren't really clear to me, for which even just a link to an online article could be useful. I'll put them all here, in random order, then let's see what should be written on a README and what could be put into comments on the code.

- with `prerender-spa` solution, there wasn't a css optimization step (at least, I didn't need to configure it in any way, if it was there), an explanation of what does criticalCss does, why preload is useful and the differences between different strategies could be useful
- seems like `criticalCss.preload` should only be asked when `criticalCss.enable` is true, right? But right now it's asked always
- `fallback` prompts confuse me: after the initial download of the page, shouldn't the SPA automatically be mounted? What do you mean by `Enable fallback SPA` then? I can see it's related to the "Not Found" page, but couldn't it just be a prerendered 404 page too, which then gets enhanced to a SPA?
- what about 'bodyClasses' boot file? What's the problem it's solving?
- could be useful to provide a reference about what options `src-static/rendererOptions.js` can be used to configure
- more a confirmation than a question: `ssrUpdate()`, `<script>` tags deferring and `data-server-rendered="true"` addition, which had to be done manually when using `prerender-spa` solution, are already taken care by Quasar SSR, right?

**Comment by freddy38510** [comment]
Thanks for all your feedbacks @IlCallo 

The extension was initially written for my specific needs. Some of them was to inline my critical CSS and lazy-load the rest. For that i forked [Critters](https://github.com/GoogleChromeLabs/critters) to have the ability to do all these steps at build time instead of doing it with a webpack plugin like Critters does.
You could see all the strategies [here](https://github.com/GoogleChromeLabs/critters#preloadstrategy).
I think this has nothing to do with the goal of our extension. It would rather be an other extension.

> seems like criticalCss.preload should only be asked when criticalCss.enable is true, right? But right now it's asked always

You're right about that, it was a mistake from myself.

For the SPA fallback, you're right again, the SPA is automatically mounted after the first load of a page, then for subsequents navigations. But, in case the page does not exist (no index.html file found by the server for the current route), instead of returning a static 404 page, we return a page generated in SPA mode. This is the same mechanism used by Nuxt, there is some documentation [here](https://nuxtjs.org/api/configuration-generate/#fallback)

For bodyClasses boot files, this is just a workaround for adding [classes to body ](https://quasar.dev/style/body-classes) at client side. Normally, with SSR mode the server know which is the platform of the client (by extracting it from User-Agent header). But in our case, we doing it at build time, so we don't have the correct platform of the client. See this [file](https://github.com/quasarframework/quasar/blob/dev/ui/src/body.js) for reference.

`defer` and `data-server-rendered` attributes are added by **vue-server-renderer**. See [here](https://ssr.vuejs.org/guide/hydration.html) and [here](https://ssr.vuejs.org/guide/build-config.html#client-config).

**Comment by IlCallo** [comment]
I'll get back to testing the AE as soon as possible, right now the coronavirus throw everything upside down here in Italy and I don't have much time to check this out further :sweat_smile:

**Comment by cabassi** [comment]
@freddy38510 @IlCallo 
> For the SPA fallback, you're right again, the SPA is automatically mounted after the first load of a page, then for subsequents navigations.

I've got a question about that:
Let's say we're building a website using vue and quasar that loads its content using an headless cms; can't we pre render all the pages instead of going to SPA mode after the first page has been loaded?
Should't this approach improve navigation speed since all the pages are prerendered?

I'm going to use this in a few projects at my company so let me know if I can help with something ;)

**Comment by IlCallo** [comment]
@cabassi SPA allow you to load only the changing data (and if you use routing with dynamic imports, only the right bundle is loaded at any time), fully reloading the page will need html and css processing every time, that cannot be faster.

SSG minimise the page first load time, then you get SPA and all goodies which comes with it

Anyway, you can just avoid using Vue router, use plain links between pages and you'll get what you want, I think

**Comment by freddy38510** [comment]
There is one caveat if you're fetching data from an external API. The data in your prerendered pages can be older than the data fetched by the client.

Solutions:
1. You can prefetch and store the data in a json file for each page at build time, then fetch these files at client side or import them to your bundle. For better performance you can also use code splitting and dynamic import of your json files.
You can take inspiration from this [Nuxt module](https://github.com/DreaMinder/nuxt-payload-extractor).

2. You can prefetch your data in your Vuex store. At server side (so at build time in our case), the state will be automatically embedded in the final HTML of each page. On the client, the store should pick up the state before mounting the application.
See the documentation from the [Vue SSR Guide](https://ssr.vuejs.org/guide/data.html#data-store).
I think that the [prefetch feature](https://quasar.dev/quasar-cli/cli-documentation/prefetch-feature#Introduction) from Quasar could be useful in this scenario.

**Comment by cabassi** [comment]
Thanks @IlCallo and @freddy38510 for the helpful suggestions :) 
I‘ll try the solutions you suggested
